//
//  skill-list.h
//  wsg
//
//  Created by 周志超 on 16/7/5.
//  Copyright © 2016年 Cosim Studio. All rights reserved.
//

#ifdef WSG_DSKN
#define __WSG__SKILL__LIST__NEEDED__H__
#endif//WSG_DSKN
#ifdef __WSG__SKILL__LIST__NEEDED__H__

WSG_DSKN(NONE),
WSG_DSKN(ANXU),            //YJ101      步练师-安恤
WSG_DSKN(BAIYIN),          //LE008      司马懿-拜印
WSG_DSKN(BAONVE),          //QUN006     董卓-[暴虐]
WSG_DSKN(BAZHEN),          //SHU011     诸葛亮-八阵
WSG_DSKN(BEIGE),           //QUN012     蔡文姬-悲歌
WSG_DSKN(BENGHUAI),        //QUN006     董卓-崩坏
WSG_DSKN(BIYUE),           //QUN003     貂蝉-闭月
WSG_DSKN(BUQU),            //WU013      周泰-不屈
WSG_DSKN(BUYI),            //YJ007      吴国太-补益
WSG_DSKN(CHONGZHEN),       //XSP001     赵云-冲阵
WSG_DSKN(CHUNLAO),         //YJ103      程普-醇醪
WSG_DSKN(DAHE),            //XSP005     张飞-大喝
WSG_DSKN(DANGXIAN),        //YJ107      廖化-当先
WSG_DSKN(DANJI),           //SP007      关羽-单骑
WSG_DSKN(DANLAO),          //SP001      杨修-啖酪
WSG_DSKN(DAWU),            //LE004      诸葛亮-大雾
WSG_DSKN(DIMENG),          //WU014      鲁肃-缔盟
WSG_DSKN(DUANCHANG),       //QUN012     蔡文姬-断肠
WSG_DSKN(DUANLIANG),       //WEI010     徐晃-断粮
WSG_DSKN(ENYUAN),          //YJ003      法正-恩怨
WSG_DSKN(FANGQUAN),        //SHU013     刘禅-放权
WSG_DSKN(FANJIAN),         //WU005      周瑜-反间
WSG_DSKN(FANKUI),          //WEI002     司马懿-反馈
WSG_DSKN(FANZHU),          //WEI014     曹丕-放逐
WSG_DSKN(FEIYING),          //LE005      曹操-飞影
WSG_DSKN(FUHUN),           //YJ104      关兴&张苞-父魂
WSG_DSKN(FULI),            //YJ107      廖化-伏枥
WSG_DSKN(GANGLIE),         //WEI003     夏侯惇-刚烈
WSG_DSKN(GANLU),           //YJ007      吴国太-甘露
WSG_DSKN(GONGJI),          //YJ105      韩当-弓骑
WSG_DSKN(GONGXIN),         //LE002      吕蒙-攻心
WSG_DSKN(GUANXING),        //SHU004     诸葛亮-观星
WSG_DSKN(GUHUO),           //QUN011     于吉-蛊惑
WSG_DSKN(GUICAI),          //WEI002     司马懿-鬼才
WSG_DSKN(GUIDAO),          //QUN010     张角-鬼道
WSG_DSKN(GUIXIN),          //LE005      曹操-归心
WSG_DSKN(GUOSE),           //WU006      大乔-国色
WSG_DSKN(GUZHENG),         //WU015      张昭&张纮-固政
WSG_DSKN(HAOSHI),          //WU014      鲁肃-好施
WSG_DSKN(HONGYAN),         //WU011      小乔-红颜
WSG_DSKN(HONGYUAN),        //VS001      诸葛瑾-弘援
WSG_DSKN(HUANGTIAN),       //QUN010     张角-[黄天]
WSG_DSKN(HUANSHI),         //VS001      诸葛瑾-缓释
WSG_DSKN(HUASHEN),         //QUN009     左慈-化身
WSG_DSKN(HUILEI),          //YJ006      马谡-挥泪
WSG_DSKN(HUJIA),           //WEI001     曹操-[护驾]
WSG_DSKN(HUNZHI),          //WU010      孙策-魂姿
WSG_DSKN(HUOJI),           //SHU011     诸葛亮-火计
WSG_DSKN(HUOSHOU),         //SHU014     孟获-祸首
WSG_DSKN(JIANG),           //WU010      孙策-激昂
WSG_DSKN(JIANGCHI),        //YJ102      曹彰-将驰
WSG_DSKN(JIANXIONG),       //WEI001     曹操-奸雄
WSG_DSKN(JIE),             //XSP005     张飞-嫉恶
WSG_DSKN(JIEFAN),          //YJ105      韩当-解烦
WSG_DSKN(JIEMING),         //WEI013     荀彧-节命
WSG_DSKN(JIEYIN),          //WU008      孙尚香-结姻
WSG_DSKN(JIJIANG),         //SHU001     刘备-[激将]
WSG_DSKN(JIJIU),           //QUN001     华佗-急救
WSG_DSKN(JILEI),           //SP001      杨修-鸡肋
WSG_DSKN(JINJIU),          //YJ004      高顺-禁酒
WSG_DSKN(JIUCHI),          //QUN006     董卓-酒池
WSG_DSKN(JIUSHI),          //YJ001      曹植-酒诗
WSG_DSKN(JIUYUAN),         //WU001      孙权-[救援]
WSG_DSKN(JIZHI),           //SHU007     黄月英-集智
WSG_DSKN(JUEJING),         //LE007      赵云-绝境
WSG_DSKN(JUEQING),         //YJ011      张春华-绝情
WSG_DSKN(JUJIAN),          //YJ009      徐庶-举荐
WSG_DSKN(JUSHOU),          //WEI011     曹仁-据守
WSG_DSKN(JUXIANG),         //SHU015     祝融-巨象
WSG_DSKN(KANPO),           //SHU011     诸葛亮-看破
WSG_DSKN(KEJI),            //WU003      吕蒙-克己
WSG_DSKN(KONGCHENG),       //SHU004     诸葛亮-空城
WSG_DSKN(KUANGBAO),        //LE006      吕布-狂暴
WSG_DSKN(KUANGFENG),       //LE004      诸葛亮-狂风
WSG_DSKN(KUANGGU),         //SHU009     魏延-狂骨
WSG_DSKN(KUIWEI),          //XSP003     曹仁-溃围
WSG_DSKN(KUROU),           //WU004      黄盖-苦肉
WSG_DSKN(LEIJI),           //QUN010     张角-雷击
WSG_DSKN(LIANHUAN),        //SHU010     庞统-连环
WSG_DSKN(LIANPO),          //LE008      司马懿-连破
WSG_DSKN(LIANYING),        //WU007      陆逊-连营
WSG_DSKN(LIEGONG),         //SHU008     黄忠-烈弓
WSG_DSKN(LIEREN),          //SHU015     祝融-烈刃
WSG_DSKN(LIHUN),           //XSP002     貂蝉-离魂
WSG_DSKN(LIHUO),           //YJ103      程普-疠火
WSG_DSKN(LIJIAN),          //QUN003     貂蝉-离间
WSG_DSKN(LIULI),           //WU006      大乔-流离
WSG_DSKN(LONGDAN),         //SHU005     赵云-龙胆
WSG_DSKN(LONGHUN),         //LE007      赵云-龙魂
WSG_DSKN(LUANJI),          //QUN004     袁绍-乱击
WSG_DSKN(LUANWU),          //QUN007     贾诩-乱武
WSG_DSKN(LUOSHEN),         //WEI007     甄姬-洛神
WSG_DSKN(LUOYI),           //WEI005     许褚-裸衣
WSG_DSKN(LUOYING),         //YJ001      曹植-落英
WSG_DSKN(MANJUAN),         //XSP004     庞统-漫卷
WSG_DSKN(MASHU),           //SHU006     马超-马术
WSG_DSKN(MENGJIN),         //QUN008     庞德-猛进
WSG_DSKN(MIJI),            //YJ110      王异-秘计
WSG_DSKN(MINGCE),          //YJ002      陈宫-明策
WSG_DSKN(MINGZHE),         //VS001      诸葛瑾-明哲
WSG_DSKN(MOUDAN),          //XSP006     吕蒙-谋断
WSG_DSKN(NIEPAN),          //SHU010     庞统-涅槃
WSG_DSKN(PAOXIAO),         //SHU003     张飞-咆哮
WSG_DSKN(POJUN),           //YJ008      徐盛-破军
WSG_DSKN(QIANGXI),         //WEI012     典韦-强袭
WSG_DSKN(QIANXI),          //YJ109      马岱-潜袭
WSG_DSKN(QIANXUN),         //WU007      陆逊-谦逊
WSG_DSKN(QIAOBIAN),        //WEI009     张郃-巧变
WSG_DSKN(QICAI),           //SHU007     黄月英-奇才
WSG_DSKN(QICE),            //YJ111      荀攸-奇策
WSG_DSKN(QINGGUO),         //WEI007     甄姬-倾国
WSG_DSKN(QINGNANG),        //QUN001     华佗-青囊
WSG_DSKN(QINYIN),          //LE003      周瑜-琴音
WSG_DSKN(QIXI),            //WU002      甘宁-奇袭
WSG_DSKN(QIXING),          //LE004      诸葛亮-七星
WSG_DSKN(QUANJI),          //YJ012      钟会-权计
WSG_DSKN(QUHU),            //WEI013     荀彧-驱虎
WSG_DSKN(RENDE),           //SHU001     刘备-仁德
WSG_DSKN(RENJIE),          //LE008      司马懿-忍戒
WSG_DSKN(ROULIN),          //QUN006     董卓-肉林
WSG_DSKN(RUOYU),           //SHU013     刘禅-[若愚]
WSG_DSKN(SHANGSHI),        //YJ011      张春华-伤逝
WSG_DSKN(SHELIE),          //LE002      吕蒙-涉猎
WSG_DSKN(SHENFEN),         //LE006      吕布-神愤
WSG_DSKN(SHENJI),          //SP008      吕布-神戟
WSG_DSKN(SHENSU),          //WEI008     夏侯渊-神速
WSG_DSKN(SHENWEI),         //SP008      吕布-神威
WSG_DSKN(SHIYONG),         //YJ106      华雄-恃勇
WSG_DSKN(SHUANGXIOANG),    //QUN005     颜良&文丑-双雄
WSG_DSKN(SONGWEI),         //WEI014     曹丕-[颂威]
WSG_DSKN(TANHU),           //XSP006     吕蒙-探虎
WSG_DSKN(TIANDU),          //WEI006     郭嘉-天妒
WSG_DSKN(TIANXIANG),        //WU011      小乔-天香
WSG_DSKN(TIANYI),          //WU012      太史慈-天义
WSG_DSKN(TIAOXIN),         //SHU012     姜维-挑衅
WSG_DSKN(TIEJI),           //SHU006     马超-铁骑
WSG_DSKN(TUNTIAN),         //WEI015     邓艾-屯田
WSG_DSKN(TUXI),            //WEI004     张辽-突袭
WSG_DSKN(WANSHA),          //QUN007     贾诩-完杀
WSG_DSKN(WEIDI),           //SP004      袁术-伪帝
WSG_DSKN(WEIMU),           //QUN007     贾诩-帷幕
WSG_DSKN(WUHUN),           //LE001      关羽-武魂
WSG_DSKN(WUMOU),           //LE006      吕布-无谋
WSG_DSKN(WUQIAN),          //LE006      吕布-无前
WSG_DSKN(WUSHEN),          //LE001      关羽-武神
WSG_DSKN(WUSHENG),         //SHU002     关羽-武圣
WSG_DSKN(WUSHUANG),        //QUN002     吕布-无双
WSG_DSKN(WUYAN),           //YJ009      徐庶-无言
WSG_DSKN(XIANGLE),         //SHU013     刘禅-享乐
WSG_DSKN(XIANZHEN),        //YJ004      高顺-陷阵
WSG_DSKN(XIAOJI),          //WU008      孙尚香-枭姬
WSG_DSKN(XINGSHUANG),      //WEI014     曹丕-行殇
WSG_DSKN(XINSHENG),        //QUN009     左慈-新生
WSG_DSKN(XINZHAN),         //YJ006      马谡-心战
WSG_DSKN(XIULUO),          //SP008      吕布-修罗
WSG_DSKN(XUANFENG),        //YJ005      凌统-旋风
WSG_DSKN(XUANHUO),         //YJ003      法正-眩惑
WSG_DSKN(XUEYI),           //QUN004     袁绍-[血裔]
WSG_DSKN(YANZHENG),        //XSP003     曹仁-严整
WSG_DSKN(YEYAN),           //LE003      周瑜-业炎
WSG_DSKN(YICONG),          //SP003      公孙瓒-义从
WSG_DSKN(YIJI),            //WEI006     郭嘉-遗计
WSG_DSKN(YINGHUN),         //WU009      孙坚-英魂
WSG_DSKN(YINGZI),          //WU005      周瑜-英姿
WSG_DSKN(YIZHONG),         //YJ010      于禁-毅重
WSG_DSKN(YONGSI),          //SP004      袁术-庸肆
WSG_DSKN(ZAIQI),           //SHU014     孟获-再起
WSG_DSKN(ZAOXIAN),         //WEI015     邓艾-凿险
WSG_DSKN(ZHENLIE),         //YJ110      王异-贞烈
WSG_DSKN(ZHIBA),           //WU010      孙策-[制霸]
WSG_DSKN(ZHICHI),          //YJ002      陈宫-智迟
WSG_DSKN(ZHIHENG),         //WU001      孙权-制衡
WSG_DSKN(ZHIJI),           //SHU012     姜维-志继
WSG_DSKN(ZHIJIAN),         //WU015      张昭&张纮-直谏
WSG_DSKN(ZHIYU),           //YJ111      荀攸-智愚
WSG_DSKN(ZHUIYI),          //YJ101      步练师-追忆
WSG_DSKN(ZILI),            //YJ012      钟会-自立(排异)
WSG_DSKN(ZISHOU),          //YJ108      刘表-自守
WSG_DSKN(ZONGSHI),         //YJ108      刘表-宗室
WSG_DSKN(ZUIXIANG),        //XSP004     庞统-醉乡

WSG_DSKN(CHENGXIANG),      //YJ201      曹冲-称象
WSG_DSKN(RENXIN),          //YJ201      曹冲-仁心
WSG_DSKN(ZHUIKONG),        //YJ202      伏皇后-惴恐
WSG_DSKN(QIUYUAN),         //YJ202      伏皇后-求援
WSG_DSKN(LONGYIN),         //YJ203      关平-龙吟
WSG_DSKN(JINGCE),          //YJ204      郭淮-精策
WSG_DSKN(QIAOSHUI),        //YJ205      简雍-巧说
WSG_DSKN(ZONGSHI_JY),      //YJ205      简雍-纵适
WSG_DSKN(JUECE),           //YJ206      李儒-绝策
WSG_DSKN(MIEJI),           //YJ206      李儒-灭计
WSG_DSKN(FENCHENG),        //YJ206      李儒-焚城
WSG_DSKN(XIANSI),          //YJ207      刘封-陷嗣
WSG_DSKN(JUNXING),         //YJ208      满宠-峻刑
WSG_DSKN(YUCE),            //YJ208      满宠-御策
WSG_DSKN(DUODAO),          //YJ209      潘璋&马忠-夺刀
WSG_DSKN(ANJIAN),          //YJ209      潘璋&马忠-暗箭
WSG_DSKN(ZONGXUAN),        //YJ210      虞翻-纵玄
WSG_DSKN(ZHIYAN),          //YJ210      虞翻-直言
WSG_DSKN(DANSHOU),         //YJ211      朱然-胆守
WSG_DSKN(XINGWU),          //SP021      大乔&小乔-星舞
WSG_DSKN(YANLUO)           //SP021      大乔&小乔-雁落


#endif /* __WSG__SKILL__LIST__NEEDED__H__ */